# common/handlers/main.yml
---

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
