# common/handlers/main.yml
---

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reboot server
  shell: "sleep 2 && /usr/sbin/shutdown -r now 'Maintenance reboot'"
  ignore_errors: yes
  async: 1
  poll: 0
